Metaswitch/ellis

root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config

Andy,
This is the second part (first part: https://github.com/Metaswitch/clearwater-nginx/pull/13) of my change that fixes #91.
This makes ellis the default server and (just for completeness really) adds its public hostname as a virtual host.
As for the first part, this has been live tested in various deployment types.
Matt

[Reviewer: Andy] Mark ellis as the default server

---

mysql.monit

As discussed, this line looks wrong - monit shouldn't kill mysql just because system load has gone above 10% for a few minutes. Fully tested and documented.

Reviewer AMC: Monit, don't kill mysql if system load goes above 10%

---

src/metaswitch/ellis/test/api/numbers.py

I ran 'make test' in Ellis and found that one test actually tried to contact homer.cw-ngv.com (which was unreachable, so the test failed). This change mocks it out.

[Reviewer: Andy] Mock out put_simservs in one test where it was missed

---

debian/ellis.init.d

This PR makes Ellis's init script wait until Ellis's tools have exited before stopping the Ellis server. This is needed because the way that we stop Ellis is by terminating all processes that are using it's pytyhon executable, which includes tools like `create_numbers.py`. This in turn is breaking AIO node installs. 
The fix only waits for tools run from the `/usr/share/clearwater/ellis` directory, but that is enough to fix the AIO, and reduces the chance of false positives.
Tested by:
* Running `create_numbers.py` and `sudo service ellis restart` in parallel. The restart waits until `create_numbers.py` has finished.
* Running `sudo service ellis restart` on its own returned promptly.
* Using chef to spin up an AIO node.

[Reviewer: Rob] Wait for Ellis's tools to exit before stopping the server

---

src/metaswitch/ellis/tools/create_numbers.py

Fixes https://github.com/Metaswitch/ellis/issues/58. I've tested live.

[Reviewer: Matt] Remove restriction that all Ellis numbers must be 10 digits

---

src/metaswitch/ellis/prov_tools/create_user.py
src/metaswitch/ellis/prov_tools/display_user.py
src/metaswitch/ellis/prov_tools/update_user.py
src/metaswitch/ellis/prov_tools/utils.py
src/metaswitch/ellis/remote/homestead.py
src/metaswitch/ellis/test/remote/homestead.py

Ellie,
Please can you review my fix to enhance provisioning tools to support plaintext passwords?
Tested live (as well as UT below):
```
$ ./create_user --plaintext 111111 mirw.cw-ngv.com secret
111111@mirw.cw-ngv.com:
HA1 digest:
6086e9f631bf739e7bb06f252b2f590b (secret)
iFC:
<?xml version="1.0" ?>
<ServiceProfile>
</ServiceProfile>
```
(Also works for update_user and display_user.)
Cheers,
Matt

[Reviewer: Ellie] Enhance provisioning tools to support plaintext passwords

---

clearwater-prov-tools.root/usr/share/clearwater/bin/list_users
src/metaswitch/ellis/prov_tools/create_user.py
src/metaswitch/ellis/prov_tools/list_users.py
src/metaswitch/ellis/prov_tools/update_user.py
src/metaswitch/ellis/prov_tools/utils.py
src/metaswitch/ellis/remote/homestead.py
src/metaswitch/ellis/test/remote/homestead.py

Rob,
Please can you review these changes for the `list_users` tool?
The bulk of the changes are in the `list_users.py` and `utils.py` file, but a few other points.
*   `utils.display_user` no longer takes the `private_id`, instead looking it up from the server, and displaying all that it finds
*   I've enhanced `homestead.http_request` and `homestead._sync_http_request` to retry (after a delay) if they get a 503 overload response - as well as improving behavior here, this improves ellis generally - the bulk of the UT cases are actually around this.
I've UT-ed and live-tested.  Docs will follow tomorrow.
Matt

[Reviewer: Rob] Implement list_users tool

---

.gitignore
Makefile
clearwater-prov-tools.root/usr/share/clearwater/bin/create_user
clearwater-prov-tools.root/usr/share/clearwater/bin/delete_user
clearwater-prov-tools.root/usr/share/clearwater/bin/display_user
clearwater-prov-tools.root/usr/share/clearwater/bin/list_users
clearwater-prov-tools.root/usr/share/clearwater/bin/update_user
clearwater-prov-tools.root/usr/share/clearwater/infrastructure/scripts/clearwater-prov-tools
debian/clearwater-prov-tools.install
debian/clearwater-prov-tools.postinst

This moves clearwater-prov-tools to the new build infrastructure (i.e. build all the eggs locally then just install them). As a side effect, it;'s tricky to hardcode exact paths, so /usr/share/clearwater/bin/create_user etc. look a bit different (they're short scripts that invoke Python rather than symlinks).
You can re-enable live-test-docker when you've reviewed.

[Reviewer: Andy] Move to new build infrastructure

---

docs/api.md
docs/features.md
src/metaswitch/ellis/api/session.py
src/metaswitch/ellis/test/api/session.py

Fixes https://github.com/Metaswitch/ellis/issues/67- JSON is always supported I'm fairly sure. I've included an example curl command now so that future users don't have the seem difficulties you apparently had. I could have done the same for all the commands, but I think people can add them if and when they ever use them (i.e. never).
Fixes https://github.com/Metaswitch/ellis/issues/69 - fixed by changing the docs.
Fixes https://github.com/Metaswitch/ellis/issues/70 - I've corrected PSTN to PSTN number in the API doc and adding a sentence about what a PSTN number actually means for Ellis. Should clear any confusion right up.
Fixes https://github.com/Metaswitch/ellis/issues/71 - just changed API to say 302 rather than 301.
Fixes https://github.com/Metaswitch/ellis/issues/72 - as far as I …

Reviewer RKD: Various API fixes

---

src/metaswitch/ellis/api/_base.py

Account deletion returns 204 No Content but a body of '{}', that's terribly sad (and breaks the Java Apache HttpComponents client), this fixes it and stops us getting it wrong again.

[Reviewer: Graeme] Honour the spirit of the 204 No Content response

---

src/metaswitch/ellis/data/numbers.py
src/metaswitch/ellis/test/data/numbers.py

Allocate numbers in Ellis's database as they are selected (rather than doing it in two phases which is susceptible to races).
Fix suggested by @mbt-msw who's tested it live (and I've updated the UTs to match).

Reviewer Rob - Select and allocate numbers from the database atomically

---

debian/ellis.init.d
setup.py
src/metaswitch/ellis/main.py
src/metaswitch/ellis/settings.py

This PR:
* makes the main Ellis process write out a pidfile (with file locking so it can't be trampled)
* makes start-stop-daemon monitor and kill Ellis with that pidfile
* sets a parent death signal in the child processes, so that they get a SIGTERM when their parent dies
* renames the process from "python" to "ellis" - not for start-stop-daemon purposes, but for diagnostics
* adds prctl as a dependency

[Reviewer: Matt] More robustness in start-stop-daemon

---

src/metaswitch/ellis/prov_tools/utils.py

Hi Andy,
This a fix to the error logging if we receive a 404 response to requesting the private ID in utils.display_user.
Tested on a test deployment.

[Reviewer Andy] Fix TypeError when receiving 404 for getting private IDs

---

clearwater-prov-tools.root/usr/share/clearwater/infrastructure/scripts/clearwater-prov-tools

Hi Andy,
This is a proposed fix for #144. I've tested it on our test system. Please could you review?
I am a little concerned that this change means that the 'local_settings' file is always created by this script and thus we will always overwrite the defaults in 'settings.py' such as 'XDM_URL=homer.cw-ngv.com:7888' with E.g. 'XDM_URL=MUST_BE_CONFIGURED' and so this change may have consequences that I've not considered.
I think that making it clear when these values have not been configured manually is a good thing, but I don't know if you rely on the defaults currently in use.

[Reviewer: Matt] Improve prov-tools local_settings creation. Fixes #144

---

src/metaswitch/ellis/prov_tools/utils.py

Hi Andy,
This fixes an issue where trying to create a user with an IFC file fails with exit code 1. Tested live.
Cheers,
Tom

[Reviewer Andy] Fix read ifc from file

---

src/metaswitch/ellis/prov_tools/utils.py

Hi Andy,
This is a fix to create_user (and others) stripping any prefix from the front of numbers caused by our prefix match regex using end-of-line, '$', instead of start-of-line, '^'.
Tested on our test system.

[Reviewer: Andy] Correct prefix regex to start at start of string

---

src/metaswitch/ellis/prov_tools/update_user.py

This change adds the ability to update_user to modify the iFC file of a subscriber added through create_user.  As update_user is now no longer solely for the purpose of updating the password, the password field becomes an optional parameter in update_user (and requires a "--password" option to be specified in front of the new password if it is to be changed).
The change also tidies away a spurious "plaintext=.." in the arguments to a function call.
Tested using an iFC file with DOMAIN and PREFIX substitute strings to confirm that the new --prefix option also works.  Each of the three update options (password changed only, iFC changed only, both password and iFC changed) was tested, as was the "iFC file missing" error path and the defaulting of prefix to "123".

[Reviewer AMC] Allow iFC to be changed by update_user

---

src/metaswitch/ellis/prov_tools/create_user.py
src/metaswitch/ellis/prov_tools/utils.py

Hi Andy,
The context for this fix is that running `create_user` for a user that already exists gives the error 
> ERROR: Private ID num@example.com already exists - not creating
which is then swamped off the screen by displaying the data stored for the existing user, including iFC.
Additionally, I added an extra error to the `display_user` and `update_user` scripts when all requests return 404, to suggest that the user likely doesn't exist - as opposed to some freak database corruption leaving only partial user data. The old error message was:
>ERROR: Failed to retrieve iFC for public ID sip:num@example.com - HTTP status code 404
Tested on a test box. Please could you review?
Thanks,
Tom

[Reviewer: Andy] Improve Homestead-prov script's UX

---

src/metaswitch/ellis/prov_tools/utils.py

Hi Andy,
This is a fix for an issue that causes leading 0s to be stripped off the numbers of created users. Additionally I fixed a bug causing a MemoryError when trying to provision a large number of subscribers.
Tested live.
Thanks,
Tom

Reviewer: AMC] Preserve leading 0 on create user

---

root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config
src/metaswitch/ellis/api/_base.py
src/metaswitch/ellis/main.py
src/metaswitch/ellis/remote/homestead.py
src/metaswitch/ellis/remote/xdm.py

This makes some logging/error reporting fixes I thought would be useful while investigating https://github.com/Metaswitch/ellis/issues/174.
I'll test by:
* marking a number as created in the Ellis database, but not creating it in Homestead
* running the live tests, which will try to clean up that number and fail
* checking that my logs do what I'd expect

[Reviewer: Ellie] Better logging for Homestead/Homer failures

---

src/metaswitch/ellis/api/numbers.py
src/metaswitch/ellis/test/api/test_numbers.py

This should fix #174.
I'll test by:
* marking a number as created in the Ellis database, but not creating it in Homestead
* running the live tests, which will try to clean up that number
* checking that the live tests don't report an error, and that number is freed up in Ellis' database

[Reviewer: Ellie] Clear out failed numbers if Homestead doesn't know about them

---

root/usr/share/clearwater/bin/poll_ellis.sh
root/usr/share/clearwater/bin/poll_ellis_https.sh

Same as https://github.com/Metaswitch/clearwater-infrastructure/pull/332, but for this repo.

Switch from Python version of bracket_ipv6_address to C++ version

---

debian/clearwater-prov-tools.postinst
debian/ellis.postinst

Rob,
Please can you review this fix to https://github.com/Metaswitch/crest/issues/271?  I've tested live.
One thing I'm not sure about is whether we should apply `--always-unzip` to other packages?  It doesn't seem required, but it might be best for consistency - thoughts?
Matt

[Reviewer: Rob] Use --always-unzip to avoid needing to run tools as a particular user

---

Makefile
docs/development.md

Rob, can you please review this, as you make the changes to remove `setup.py install` from the postinst scripts. The first commit just contains whitespace changes.
Remove the steps after `make env` in the build process.
`easy_install` is already run as part of `make env`, but with the
correct args.
The `setup.py` commands were taken from the postinst scripts. They
have since been removed as they are no longer needed. Let's remove
them from here too.

[Reviewer: Rob] Docs fix

---

src/metaswitch/ellis/api/_base.py

Fixes a case where we tried to print the url before it had been set.

[Reviewer: Rob] Make sure url is always set

---

debian/ellis.init.d
docs/development.md
src/metaswitch/ellis/main.py
src/metaswitch/ellis/settings.py

Use Clearwater's user settings for the log level, instead of local_settings.py.

[Reviewer: Ellie] Use Clearwater's user settings for the log level

---

setup.py

Rob,
This fixes https://github.com/Metaswitch/ellis/issues/188 by making pycurl an explicit dependancy of ellis.
pycurl is required because we explicitly require it to be installed for sync_database.py -https://github.com/Metaswitch/ellis/blob/dev/src/metaswitch/ellis/tools/sync_databases.py#L53
I've also marked everything as an explicit version -for the missing ones,  I've just taken the versions that were installed by default when I built.

[Reviewer: RKD] Add pycurl as a explicit dependancy

---

root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config

This accompanies the change to the `ping` service in clearwater-nginx, see PR: Metaswitch/clearwater-nginx#46
This server relied on the `ipv6only=off` flag that was set in `ping`, which was also applied to Ellis after the two configs were merged, as they listened on the same address and port. With the above PR, `ping` will no longer be listening on the same address and port, so `ipv6only=off` must be specified.
I've tested this change directly by editing the `/etc/nginx/sites-available/ellis` file on an AWS PC deployment (along with the nginx change in the above PR). It is worth noting that this change will require a restart to clearwater-infrastructure to be picked up when a node upgrades to the new Ellis package.

[Reviewer: RJW2] Specify ipv6only=off in ellis nginx config

---

src/metaswitch/ellis/prov_tools/create_user.py

This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/2269
It adds some output to the create_user script:
- we print a `.` to the screen for every DN that we attempt to create
- for every 10 DN that we've attempted, we print where we've got to so the user can see how far through the script has got
In combination, these two make it clear that the script is doing something and give a sense of the progress made so far.
The output looks like:
```
[dime-1]ubuntu@ec2-34-235-166-72:~$ /usr/share/clearwater/bin/create_user 3055555001..3055556000 sr2.cw-ngv.com secret
Creating users.......................................................................................................
Created up to user 3055555100
.................................................................. …
```

[Reviewer: Adam] Add some output to create_user

---

src/metaswitch/ellis/remote/homestead.py
src/metaswitch/ellis/test/remote/homestead.py

When using `cw-create_user` I would often see the following error log in homestead-prov:
```
Translating internal <class 'telephus.cassandra.ttypes.TimedOutException'> error into a 503 status code
```
It looks like Cassandra is overloaded which results in timeouts. The behaviour of the create_user script on receiving a 503 is to wait 500ms then retry. If it receives a second 503, it waits a further 500ms and then retries again. Any further failures and it gives up on the request which eventually causes the script to fail.
This PR backs off the retry interval so that we actually give Cassandra a chance to recover before trying again. I no longer saw multiple 503s cause a failure after this change.

[Reviewer: EM] Retry less aggresively on 503

---

Makefile

Seb,
This resolves a problem where the common wheel isn't rebuilt when required, causing builds to fail.
I've tested this by:
- Running `make deb` and checking it built everything.
- Re-running `make deb` and checking it didn't rebuild anything
- Touching `src/metaswitch/ellis/main.py`, rerunning `make deb` and checking everything get's correctly rebuilt.

[Reviewer: Seb] Rebuild the common wheel if it's cleaned

---

src/metaswitch/ellis/prov_tools/utils.py
src/metaswitch/ellis/remote/homestead.py

Hi Krista, would you mind reviewing this?
This fix addresses Issue 514812, where a user created in homestead-prov with malformed XML file containing the Initial Filter Criteria (IFC) could not be deleted.
The fix doesn't fix the delete user script itself, instead it prevents the problem from arising in the first place. It does this by not allowing a malformed XML file containing the IFC to be uploaded to the subscriber database. The code that does this simply throws a ValueError and lets the client side (i.e. the create_user.py script) handle the error appropriately. In this case, the user simply is not created (the build_ifc function in utils.py returns 'None' which leads to sys.exit(1) in the create_user.py script).
I have tested the code without including the change to the client side …

[Reviewer: KH1] Cannot delete user in dgn

---

src/metaswitch/ellis/test/remote/homestead.py

This is a UT that tests creation of user with malformed iFC.

Homestead cw-create_user with malformed iFC - Unit Test

---

src/metaswitch/ellis/prov_tools/create_user.py

This PR adds the ability to set the IMPI when creating a user.
Users pass in --impi <impi> as a parameter to create_user. If they don't, the IMPI is derived from the IMPU.
The IMPI is at the same level as the password - so if you are creating a range of users then they'll all have the same IMPI - this is a bit rubbish, but it's sufficient for the use case.
Tested live (there aren't any UTs).

[Reviewer: Sathiyan] Add setting the IMPI

---

src/metaswitch/ellis/prov_tools/create_user.py
src/metaswitch/ellis/prov_tools/delete_user.py
src/metaswitch/ellis/prov_tools/update_user.py

This fixes the pub/priv ID order in create user, and adds the IMPI option to the other prov scripts (in the same way as for create_user).

[Reviewer: Sathiyan] Add IMPI option to the other scripts, and fix create_user
