- debian/ellis.prerm
Don't remove ellis user on upgrade. Do delete ellis sockets unless we're upgrading.
I haven't tested this yet, I just wanted you to check I was doing roughly the right thing.
> DO NOT MERGE: Reviewer AMC: Tweak prerm script

- ellis.monit
- mysql.monit
- root/usr/share/clearwater/bin/poll_ellis.sh
Ellis/MySQL changes (following template of https://github.com/Metaswitch/chronos/pull/107)
> [Reviewer: Matt] Monit changes

- docs/development.md
> [No reviewer] Add in setup scripts

- docs/api.md
Updates the Ellis API docs to cover the feature I added in https://github.com/Metaswitch/ellis/pull/61.
I've also deleted two parts where we described function we hadn't implemented - I thought this was confusing.
> [Reviewer: Ellie] Update API docs to cover specific numbers

- src/metaswitch/ellis/api/numbers.py
- src/metaswitch/ellis/test/api/numbers.py
Fixes https://github.com/Metaswitch/ellis/issues/68. UTed, not tested live.
> [Reviewer: Andy] Allow 'pstn' to be 'true', 'True', 'trUe' etc.

- debian/ellis.init.d
Same as https://github.com/Metaswitch/homestead/pull/207.
> [Reviewer: Andy] Add service run command to run blocking

- root/etc/cron.hourly/ellis-log-cleanup
- src/metaswitch/ellis/api/_base.py
- src/metaswitch/ellis/api/numbers.py
- src/metaswitch/ellis/main.py
- src/metaswitch/ellis/tools/create_numbers.py
- src/metaswitch/ellis/tools/sync_databases.py
This is the corresponding Ellis change to the python-common one.
> [Reviewer: Alex] Update to match logging and utils changes

- backup/restore_backup.sh
- ellis.monit
- mysql.monit
Metaswitch/clearwater-monit#16
> [No reviewer] Add in groups

- debian/ellis.postinst
- root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config
Familiar fix... This is the last one.
> Reviewer Ellie - Activate nginx config in infrastrucutre script

- root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config
Port of https://github.com/Metaswitch/crest/pull/211.
> No review required - Diff against the symlink, not the main file

- buildout.cfg
Matching fix to https://github.com/Metaswitch/crest/pull/212
> [No reviewer] Mock

- src/metaswitch/ellis/api/__init__.py
- src/metaswitch/ellis/api/_base.py
- src/metaswitch/ellis/api/numbers.py
- src/metaswitch/ellis/api/users.py
- src/metaswitch/ellis/data/__init__.py
- src/metaswitch/ellis/data/users.py
- src/metaswitch/ellis/mail/mail.py
- src/metaswitch/ellis/main.py
- src/metaswitch/ellis/test/__init__.py
- src/metaswitch/ellis/test/api/numbers.py
- src/metaswitch/ellis/test/api/session.py
- src/metaswitch/ellis/test/api/users.py
- src/metaswitch/ellis/test/api/validation.py
- src/metaswitch/ellis/test/data/numbers.py
- src/metaswitch/ellis/test/data/users.py
- src/metaswitch/ellis/test/mail/mail.py
- src/metaswitch/ellis/test/remote/homestead.py
- src/metaswitch/ellis/tools/create_numbers.py
- src/metaswitch/ellis/tools/sync_databases.py
Final set of make verify fixes
> [Reviewer: Rob] Make verify fixes

- local_settings.py
- root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config
- root/usr/share/clearwater/infrastructure/scripts/ellis
Similar fix to https://github.com/Metaswitch/crest/pull/229
> [No reviewer] Check for config before running scripts

- debian/clearwater-prov-tools.postinst
> [No reviewer] Don't error if the log file already exists

- debian/control
- root/etc/cron.hourly/ellis-log-cleanup
I'm taking names here, big fix
> Reviewer RKD: Log cleanup

- src/metaswitch/ellis/test/api/users.py
Fixing UTs that @rkd-msw broke. That's @rkd-msw.
> No reviewer: Fix broken UTs

- root/usr/share/clearwater/node_type.d/20_ellis
> [No reviewer] Support etcd colocation

- root/usr/share/clearwater/infrastructure/scripts/create-ellis-nginx-config
- web-content/login.html
- web-content/resetpassword.html
- web-content/signup.html
I've done the following testing using the web interface:
* Logged in with an existing account
* Created a new account and logged in with it
* Reset my password on an existing account
* Tried to create an account for a username that already exists
* Added and removed ellis_hostname in /etc/clearwater/shared_config and checked the nginx config file
> Reviewer AMC: Various fixes

- src/metaswitch/ellis/prov_tools/delete_user.py
Hi Andy,
This is an upstream merge of a fix to add a prompt to the command line 'delete_user' script. I've tested it live on our test system.
Cheers,
Tom
> [Reviewer: Andy] Add prompt to delete_user

- scripts/repop_hs.py
- scripts/repop_xdm.py
> [No reviewer] Fix up basic runtime errors

- setup.py
Pin third party code to a known version
> [No reviewer] Add explicit version constraints

- src/metaswitch/ellis/remote/homestead.py
This would have been useful answering a question on the mailing list.
> [Reviewer: Alex] Log method used in HTTP debug logs.

- src/metaswitch/ellis/prov_tools/create_user.py
- src/metaswitch/ellis/prov_tools/display_user.py
- src/metaswitch/ellis/prov_tools/update_user.py
Not merging until the release is cut.Not merging until the release is cut.
> Reviewer MIRW: [DO NOT MERGE] Remove unused script argument

- Makefile
- src/metaswitch/ellis/__init__.py
- src/metaswitch/ellis/api/__init__.py
- src/metaswitch/ellis/api/_base.py
- src/metaswitch/ellis/api/numbers.py
- src/metaswitch/ellis/api/session.py
- src/metaswitch/ellis/api/users.py
- src/metaswitch/ellis/api/utils.py
- src/metaswitch/ellis/api/validation.py
- src/metaswitch/ellis/data/numbers.py
- src/metaswitch/ellis/data/users.py
- src/metaswitch/ellis/mail/mail.py
- src/metaswitch/ellis/remote/homestead.py
Actually check coverage and report if it drops. This PR doesn't try and improve coverage at all - it just starts testing coverage, and makes it easier to tell if we drop coverage in the future
> [No reviewer] Actually check coverage and fail when it drops

- src/metaswitch/ellis/tools/create_numbers.py
- src/metaswitch/ellis/tools/sync_databases.py
Saithyan,
This fixes the problems you identified in https://github.com/Metaswitch/ellis/pull/187
I've tested by running the tools on an Ellis node. Note sync_database.py doesn't work out of the box due to https://github.com/Metaswitch/ellis/issues/188
> [Reviewer: Sathiyan] Use passed in logging level in scripts

- debian/ellis.links
Companion PR to Metaswitch/clearwater-etcd#355
> [Reviewer EM] Add /usr/bin links to commonly used scripts

- src/metaswitch/ellis/remote/homestead.py
- src/metaswitch/ellis/test/remote/homestead.py
If there are no associated implicit registration sets for a user, we want to
continue with the deletion. This can happen if creating the user was interrupted so it didn't complete - in this case, we just want to delete everything we can so the user can be re-added later.
This is a fix for https://github.com/Metaswitch/crest/issues/336
- live tested, by getting the node into the state described in the linked issue and verifying that we're able to delete the user with this fix present
- added UT that hit the exception before and now doesn't
> [Reviewer: Ellie] Prevent crash deleting user which was not added completely

- Makefile
Match change made in https://github.com/Metaswitch/crest/pull/293
> Pin setuptools

- ellis.monit
- mysql.monit
As per https://github.com/Metaswitch/sprout/pull/1863
> [No reviewer] Don't wait for 6 cycles before killing a process

- Makefile
https://github.com/Metaswitch/clearwater-etcd/pull/473
> Run Bandit analysis from python.mk as part of build process

- setup.py
- src/metaswitch/ellis/data/users.py
- src/metaswitch/ellis/test/data/users.py
Functions taken from https://github.com/Metaswitch/python-common/pull/103/files
> [Reviewer: Sathiyan] Pull in password functions

- Makefile
As per https://github.com/Metaswitch/crest/pull/366, ensure we have an up to date version of pip
> [No reviewer] Upgrade pip

- Makefile
- debian/clearwater-prov-tools.postinst
- debian/ellis.postinst
Updated Python build infrastructure - upgrade pip and fix requirement handling.
> [No reviewer] Mirror changes in crest and clearwater-etcd

- .gitignore
- Makefile
- debian/clearwater-prov-tools.install
- debian/ellis.install
Use the new common python build infrastructure in Metaswitch/clearwater-build-infra#69
> [WIP] Common build infra

- src/metaswitch/ellis/test/remote/homestead.py
These are some simple UT changes related to PR #225
> UT changes

- src/metaswitch/ellis/prov_tools/create_user.py
- src/metaswitch/ellis/remote/homestead.py
- src/metaswitch/ellis/test/remote/homestead.py
This PR strips out any retry behaviour in Ellis and the prov tools, as the retry behaviour is inconsistent, and opens us up to various unpleasant window conditions. An arguably better fix would be to improve the retry behaviour, but that's probably not worth it yet.
This also improves the logs when creating subscribers using create_user.
> [Reviewer: Sathiyan] Remove retry behaviour

- prov_tools-requirements.txt
- requirements.txt
- setup.py
- src/metaswitch/ellis/prov_tools/setup.py
- src/metaswitch/ellis/prov_tools/utils.py
- src/metaswitch/ellis/remote/homestead.py
- src/metaswitch/ellis/settings.py
> Bandit final
